EmployeeAssistance/Controllers/EditorController.cs
using EmployeeAssistance.Models;
using EmployeeAssistance.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeAssistance.Controllers
{
    public class EditorController : Controller
    {
        List<ListItem> defaultListItem = new List<ListItem>() { new ListItem() { Id = "", Value = "---select---" } };
        // GET: Search

        // GET: Editory
        public ActionResult Index()
        {
            ReaderRepository repo = new ReaderRepository();
            CategoryRepository catRepo = new CategoryRepository();
            ReaderViewModel model = new ReaderViewModel();
            model.CountryOptions = repo.GetCountry();
            model.StateOptions = defaultListItem;
            model.CityOptions= defaultListItem;
            model.CategoryOptions = catRepo.GetCategory();
            model.SubCategoryOptions = catRepo.GetSubCategory();

            return View(model);
        }

        [HttpPost]
        public ActionResult Index(ReaderViewModel model)
        {

            model.CountryOptions = defaultListItem;
            model.StateOptions = defaultListItem;
            model.CityOptions = defaultListItem;
            model.CategoryOptions = defaultListItem;
            model.SubCategoryOptions = defaultListItem;

            EditorRepository repo = new EditorRepository();
            repo.AddAssistData(model);

            CategoryRepository catRepo = new CategoryRepository();
            ReaderRepository repoReader = new ReaderRepository();
            //CategoryRepository catRepo = new CategoryRepository();
            //ReaderViewModel models = new ReaderViewModel();
            model.CountryOptions = repoReader.GetCountry();
            model.CategoryOptions = catRepo.GetCategory();
            model.SubCategoryOptions = catRepo.GetSubCategory();
          
            model.save = true;
            model.information[0].Description = "";
            return View(model);
        }
    }
}

EmployeeAssistance/Controllers/ReaderController.cs
using EmployeeAssistance.Models;
using EmployeeAssistance.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeAssistance.Controllers
{
    public class ReaderController : Controller
    {
        List<ListItem> defaultListItem = new List<ListItem>() { new ListItem() { Id = "", Value = "---select---" } };
        // GET: Reader
        public ActionResult Index()
        {
            ReaderRepository repo = new ReaderRepository();
            CategoryRepository catRepo = new CategoryRepository();
            ReaderViewModel model = new ReaderViewModel();
            model.CountryOptions = repo.GetCountry();
            model.StateOptions = defaultListItem;
            model.CityOptions = defaultListItem;
            model.CategoryOptions = catRepo.GetCategory();
            model.SubCategoryOptions = catRepo.GetSubCategory();

            return View(model);
        }

        [HttpPost]
        public ActionResult Index(ReaderViewModel model)
        {
            var repoReader = new ReaderRepository();
            CategoryRepository catRepo = new CategoryRepository();

            model.CountryOptions = repoReader.GetCountry();
            model.StateOptions = (!string.IsNullOrWhiteSpace(model.Country)) ? repoReader.GetStates(model.Country) : defaultListItem;
            model.CityOptions = (!string.IsNullOrWhiteSpace(model.State)) ? repoReader.GetCity(model.State) : defaultListItem;
            model.CategoryOptions = catRepo.GetCategory();
            model.SubCategoryOptions = defaultListItem;
            model.information = repoReader.GetRecords(model);

            return View(model);
        }

        [HttpGet]
        public JsonResult GetStates(string country)
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            ReaderRepository repo = new ReaderRepository();
            result.Data = repo.GetStates(country);
            return result;
        }

        [HttpGet]
        public JsonResult GetCities(string state)
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            ReaderRepository repo = new ReaderRepository();
            result.Data = repo.GetCity(state);
            return result;
        }

        [HttpGet]
        public JsonResult UpdateLike(string informationId)
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            ReaderRepository repo = new ReaderRepository();
            var listitem = repo.UpdateLike(informationId);
            result.Data = listitem;
            return result;
        }

    
    }
}

EmployeeAssistance/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Employee Assist</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap.min.css">
    <!-- Optional Bootstrap theme -->
    <link rel="stylesheet" href="css/bootstrap-theme.min.css">
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/Common.js"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Employee Assistance System", "Index", "Reader", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Search", "Index", "Reader")</li>
                    <li>@Html.ActionLink("Contribute", "Index", "Editor")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Employee Assistance System</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

EmployeeAssistance/Views/Shared/_Search.cshtml
@model EmployeeAssistance.Models.ReaderViewModel
<fieldset class="form-group ">
    <div class="col-sm-12">
        @*<label for="ddCountry">Country</label>*@
        @Html.LabelFor(model => model.Country)
        @Html.DropDownListFor(m => m.Country,
             new SelectList(Model.CountryOptions, "Id", "Value", Model.CountryOptions.FirstOrDefault().Id), new { @class = "form-control ", @id = "ddCountry" })

    </div>
</fieldset>
<fieldset class="form-group">
    <div class="row col-sm-6">
        <div class="col-sm-12">
            @Html.LabelFor(model => model.State)
            @Html.DropDownListFor(m => m.State,
       new SelectList(Model.StateOptions, "Id", "Value", Model.StateOptions.FirstOrDefault().Id), new { @class = "form-control ", @id = "ddState" })

        </div>
    </div>
    <div class="row col-sm-6 col-sm-offset-0">
        <div class="col-sm-12 col-sm-offset-0">
            @Html.LabelFor(model => model.City)
            @Html.DropDownListFor(m => m.City,
             new SelectList(Model.CityOptions, "Id", "Value", Model.CityOptions.FirstOrDefault().Id), new { @class = "form-control ", @id = "ddCity" })
        </div>
    </div>
</fieldset>
<fieldset class="form-group">
    <div class="row col-sm-6">
        <div class="col-sm-12">
            @Html.LabelFor(model => model.Category)
            @Html.DropDownListFor(m => m.Category,
                                    new SelectList(Model.CategoryOptions, "Id", "Value", Model.CategoryOptions.FirstOrDefault().Id), new { @class = "form-control", @id = "ddCategory" })
            @*<select name="Category" class="form-control" id="ddCategory">
                    <option>Accommodation</option>
                </select>*@
        </div>
    </div>
    <div class="row col-sm-6 col-sm-offset-0">
        <div class="col-sm-12 ">
            @Html.LabelFor(model => model.SubCategory)
            @Html.DropDownListFor(m => m.SubCategory,
                                    new SelectList(Model.SubCategoryOptions, "Id", "Value", Model.SubCategoryOptions.FirstOrDefault().Id), new { @class = "form-control", @id = "ddSubCategory" })

        </div>
    </div>
</fieldset>